//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SearchResultsSampleData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SearchResultsSampleData { }
#else

	public class SearchResultsSampleData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SearchResultsSampleData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/ZuneSocialTagger.GUIV2;component/SampleData/SearchResultsSampleData/SearchResultsSampleData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Track_Title = string.Empty;

		public string Track_Title
		{
			get
			{
				return this._Track_Title;
			}

			set
			{
				if (this._Track_Title != value)
				{
					this._Track_Title = value;
					this.OnPropertyChanged("Track_Title");
				}
			}
		}

		private string _Track_Index = string.Empty;

		public string Track_Index
		{
			get
			{
				return this._Track_Index;
			}

			set
			{
				if (this._Track_Index != value)
				{
					this._Track_Index = value;
					this.OnPropertyChanged("Track_Index");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
